name: Bug report
description: Report a bug in the template or generated integrations
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: Paste relevant Home Assistant logs.

