name: Feature request
description: Suggest an improvement to the template
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What should be added or changed?
    validations:
      required: true

